### ISSUE TITLE
Crash When Placing Rune Enchanting/Scribing Table

### ISSUE THREAD

**Issue by badooga** [brotazoa/runic_enchanting#2]
When placing a Rune Enchanting Table or Rune Scribing Table by right clicking the top or bottom of a block, the following crash occurs:

```[00:47:45] [Render thread/ERROR]: Unreported exception thrown!
java.lang.IllegalStateException: Unable to get Y-rotated facing of up
	at net.minecraft.class_2350.method_10170(class_2350.java:182) ~[client-intermediary.jar:?]
	at amorphia.runic_enchanting.blocks.RuneScribingTable.method_9605(RuneScribingTable.java:71) ~[runic_enchanting-1.0+1.20.1.jar:?]
	at net.minecraft.class_1747.method_7707(class_1747.java:123) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7712(class_1747.java:75) ~[client-intermediary.jar:?]
	at net.minecraft.class_1747.method_7884(class_1747.java:50) ~[client-intermediary.jar:?]
	at net.minecraft.class_1799.method_7981(class_1799.java:272) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41934(class_636.java:363) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41933(class_636.java:324) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_41931(class_636.java:278) ~[client-intermediary.jar:?]
	at net.minecraft.class_636.method_2896(class_636.java:323) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1583(class_310.java:1802) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1508(class_310.java:2052) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1574(class_310.java:1883) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1523(class_310.java:1181) ~[client-intermediary.jar:?]
	at net.minecraft.class_310.method_1514(class_310.java:802) ~[client-intermediary.jar:?]
	at net.minecraft.client.main.Main.main(Main.java:250) ~[minecraft-1.20.1-client.jar:?]
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:468) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74) ~[fabric-loader-0.14.22.jar:?]
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23) ~[fabric-loader-0.14.22.jar:?]
	at org.prismlauncher.launcher.impl.StandardLauncher.launch(StandardLauncher.java:88) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.listen(EntryPoint.java:126) ~[NewLaunch.jar:?]
	at org.prismlauncher.EntryPoint.main(EntryPoint.java:71) ~[NewLaunch.jar:?]
```

Placing the table by right clicking the side of a block does not crash the game and works as expected.

Tested on Fabric and Quilt 1.20.1 with only Fabric/Quilt API and Runic Enchanting installed.

**Comment by kingkuys2123** [comment]
I had the same issue too.
